### PR TITLE
Update guava

### PR DESCRIPTION
**Pull request by Yannic**
Fixes failing build

### CODE REVIEW

**Comment by kaspnilsson** [comment]
+1

**Comment by Yannic** [comment]
@cgruber Any news on this PR?

**Comment by cgruber** [comment]
Sorry, have been overloaded this quarter.  I'll try to get this done in the next few days.  I need to take this inside and then push it out and I'm OOO tomorrow.

**Comment by cgruber** [comment]
Context question... do you mean 22.0-SNAPSHOT, or do you mean 22?  Do you need unreleased functionality, or does 22.0 resolve the cygwin issue?

**Comment by Yannic** [comment]
I don't remember why I used 22.0-SNAPSHOT, but I'm sure there has been a reason. I will find out again why I didn't use 22.0 and let you know.

**Comment by cgruber** [comment]
It's possible that when you filed the pull request, 22.0 was not yet
released.  But let me know if you need post-22 functionality.

**Comment by Yannic** [comment]
The reason I uses 22.0-SNAPSHOT was that 22.0 has not been released in April. I updated this PR to use 22.0

**Comment by mkobit** [comment]
Other snapshot dependencies were removed/updated in https://github.com/google/MOE/pull/41 because it led to runtime failures

**Comment by umairaziz1** [comment]
Hello

**Pull request closed without merging**
